### ISSUE TITLE
Showing no internet connection when using certain VPN even though I'm able to access the web

### ISSUE THREAD

**Issue by nathancashion** [FuzzyIdeas/IsThereNet#8] opened 2024-06-08 19:58 UTC
I'll use CloudFlare or a personal Tailnet while out and about.

I've noticed that when my Tailscale VPN is turned on AND routed through an [exit node](https://tailscale.com/kb/1103/exit-nodes?q=exit+node) at home, IsThereNet persistently shows red as if there is no internet connection. However, I am able to access websites and my home network.

In contrast, using the CloudFlare 1.1.1.1 VPN configuration or Tailscale without the exit node routing, IsThereNet shows that I'm connected.

It's probably a fringe case, but I found it a bit odd since all other network connections work as expected even when routing through an exit node.

**Comment by alin23** [comment] 2024-06-12 18:48
Hi @nathancashion ! I'm also using Tailscale, so I tried an exit node of mine just now and I'm not seeing the red disconnected state. Only the yellow slow one because ping time has increased.

Can you watch `~/Library/Containers/com.lowtechguys.IsThereNet/Data/Library/Caches/IsThereNet.log` and see what changes when you use the exit node? 

If you see **TIMEOUT** then it means that `ping 1.1.1.1` fails. If you see **OFF** instead it means that `NWPathMonitor` is returning a broken network path. It would maybe help me troubleshoot this.

**Comment by alin23** [comment] 2024-07-18 20:55
I'm closing this since it cannot be reproduced and I have no further info or confirmation. Let me know if you need to reopen.

**Closed by alin23** 2024-07-18 20:55 UTC
